---

ansible_user: root
ansible_ssh_pass: password
# set s3-admin details either in playbooks, or define here:
admin_endpoint: https://s3-admin.example.com:19443
admin_username: sysadmin
admin_password: public
