---

# Playbook - All

- hosts: s3_admin
  vars:
    # s3-admin details are defined in group_vars/s3_admin.yml
    # alternatively, override those here:
    # admin_username: sysadmin
    # admin_password: public
    cluster:
      region: eu-1
    cmc_groups:
      - groupA
      - groupB
    cmc_users:
      user1:
        group: groupA
        cmc_pass: public
        fullname: My name is Mud
        type: User
        bucket: bucket1
      user2:
        group: groupB
        cmc_pass: public
        fullname:
        type: User
        bucket: bucket2
    storage_policies:
      rf_3:
        default: True
  roles:
    - group
    - user
    - policy
