---

- name: GET Groups
  uri:
    url: "{{ admin_endpoint }}/group/list"
    method: GET
    user: "{{ admin_username }}"
    password: "{{ admin_password }}"
    force_basic_auth: True
    validate_certs: No
    status_code: 200
    return_content: yes
  register: grouplist

#- debug: var=grouplist

- set_fact:
    cmc_groups_all: "{{ lookup('template', './group.yml.j2') }}"

#- debug: var=cmc_groups_all

- name: Create Groups
  uri:
    url: "{{ admin_endpoint }}/group"
    method: PUT
    user: "{{ admin_username }}"
    password: "{{ admin_password }}"
    force_basic_auth: True
    body_format: json
    body: "{{ lookup('template','group.j2') }}"
    headers:
      Content-Type: "application/json"
    validate_certs: No
    status_code: 200
  with_items: "{{ cmc_groups }}"
  when: item not in cmc_groups_all
